### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by heavensword** [dblock/fui#16]
execute fui find command. its list all files in the current folder, not the unused class file

**Comment by dblock** [comment]
Please provide some detail other than "it doesn't work"

**Comment by heavensword** [comment]
<img width="643" alt="screen shot 2015-10-13 at 5 53 11 pm" src="https://cloud.githubusercontent.com/assets/1754087/10451566/8338a9aa-71d3-11e5-8374-4cc9e9a31f4c.png">
This is the screenshots. It just lists all class files in the current directory. Did I use it correctly?

**Comment by yuanfeidu** [comment]
when i execute fui find command, its report an error.
error: invalid byte sequence in UTF-8

**Comment by dblock** [comment]
Can you please get a stack and a file on which fui fails? @yuanfeidu Open a new issue with a repro.
