### ISSUE TITLE
files imported within *.mm marked as unused

### ISSUE THREAD

**Issue by liaojinxing** [dblock/fui#19]
For example, a class named "Test.h" and "Test.mm".
"Test.mm" import "a.h"

However, "a.h" will be marked as unused.

**Comment by michaeleiselsc** [comment]
having this issue as well. seems like it should be a simple fix, to just add ".mm" to the list of extensions which get searched?

**Comment by dblock** [comment]
Right. Please write a spec and make a PR!

**Comment by michaeleiselsc** [comment]
i'm not trying to become a maintainer, i'm just trying to report an issue

**Comment by Shachlan** [comment]
done. https://github.com/dblock/fui/pull/24
